//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        public NhaCungCap()
        {
            this.HangHoas = new HashSet<HangHoa>();
        }
    
        public string MaNCC { get; set; }
        public string TenCongTy { get; set; }
        public string Logo { get; set; }
        public string NguoiLienLac { get; set; }
        public string Email { get; set; }
        public string DienThoai { get; set; }
        public string DiaChi { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<HangHoa> HangHoas { get; set; }
    }
}
